/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { RequestBuilder } from '../../request-builder';
import { StrictHttpResponse } from '../../strict-http-response';

export interface DeleteRegistrationElectionsRegisterNameDelete$Params {
  name: string;
}

export function deleteRegistrationElectionsRegisterNameDelete(
  http: HttpClient,
  rootUrl: string,
  params: DeleteRegistrationElectionsRegisterNameDelete$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(
    rootUrl,
    deleteRegistrationElectionsRegisterNameDelete.PATH,
    'delete'
  );
  if (params) {
    rb.path('name', params.name, {});
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

deleteRegistrationElectionsRegisterNameDelete.PATH = '/elections/register/{name}';
