/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { RequestBuilder } from '../../request-builder';
import { StrictHttpResponse } from '../../strict-http-response';

export interface UpdateElectionElectionsByNameNamePatch$Params {
  name: string;
  election_type: string;
  datetime_start_nominations: string;
  datetime_start_voting: string;
  datetime_end_voting: string;
  survey_link: string | null;
}

export function updateElectionElectionsByNameNamePatch(
  http: HttpClient,
  rootUrl: string,
  params: UpdateElectionElectionsByNameNamePatch$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, updateElectionElectionsByNameNamePatch.PATH, 'patch');
  if (params) {
    rb.path('name', params.name, {});
    rb.query('election_type', params.election_type, {});
    rb.query('datetime_start_nominations', params.datetime_start_nominations, {});
    rb.query('datetime_start_voting', params.datetime_start_voting, {});
    rb.query('datetime_end_voting', params.datetime_end_voting, {});
    rb.query('survey_link', params.survey_link, {});
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

updateElectionElectionsByNameNamePatch.PATH = '/elections/by_name/{name}';
