/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { HttpValidationError } from './models/http-validation-error';
export type { InitialOfficerInfo } from './models/initial-officer-info';
export type { OfficerInfoUpload } from './models/officer-info-upload';
export type { OfficerTermUpload } from './models/officer-term-upload';
export type { ValidationError } from './models/validation-error';
