/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { RequestBuilder } from '../../request-builder';
import { StrictHttpResponse } from '../../strict-http-response';

export interface GetOfficerInfoOfficersInfoComputingIdGet$Params {
  computing_id: string;
}

export function getOfficerInfoOfficersInfoComputingIdGet(
  http: HttpClient,
  rootUrl: string,
  params: GetOfficerInfoOfficersInfoComputingIdGet$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, getOfficerInfoOfficersInfoComputingIdGet.PATH, 'get');
  if (params) {
    rb.path('computing_id', params.computing_id, {});
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

getOfficerInfoOfficersInfoComputingIdGet.PATH = '/officers/info/{computing_id}';
