/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { RequestBuilder } from '../../request-builder';
import { StrictHttpResponse } from '../../strict-http-response';

import { InitialOfficerInfo } from '../../models/initial-officer-info';

export interface NewOfficerTermOfficersTermPost$Params {
  body: Array<InitialOfficerInfo>;
}

export function newOfficerTermOfficersTermPost(
  http: HttpClient,
  rootUrl: string,
  params: NewOfficerTermOfficersTermPost$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, newOfficerTermOfficersTermPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

newOfficerTermOfficersTermPost.PATH = '/officers/term';
