/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { RequestBuilder } from '../../request-builder';
import { StrictHttpResponse } from '../../strict-http-response';

import { OfficerTermUpload } from '../../models/officer-term-upload';

export interface UpdateTermOfficersTermTermIdPatch$Params {
  term_id: number;
  body: OfficerTermUpload;
}

export function updateTermOfficersTermTermIdPatch(
  http: HttpClient,
  rootUrl: string,
  params: UpdateTermOfficersTermTermIdPatch$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, updateTermOfficersTermTermIdPatch.PATH, 'patch');
  if (params) {
    rb.path('term_id', params.term_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

updateTermOfficersTermTermIdPatch.PATH = '/officers/term/{term_id}';
