/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { RequestBuilder } from '../../request-builder';
import { StrictHttpResponse } from '../../strict-http-response';

import { OfficerInfoUpload } from '../../models/officer-info-upload';

export interface UpdateInfoOfficersInfoComputingIdPatch$Params {
  computing_id: string;
  body: OfficerInfoUpload;
}

export function updateInfoOfficersInfoComputingIdPatch(
  http: HttpClient,
  rootUrl: string,
  params: UpdateInfoOfficersInfoComputingIdPatch$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, updateInfoOfficersInfoComputingIdPatch.PATH, 'patch');
  if (params) {
    rb.path('computing_id', params.computing_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

updateInfoOfficersInfoComputingIdPatch.PATH = '/officers/info/{computing_id}';
