/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ValidationError } from '../models/validation-error';
export interface HttpValidationError {
  detail?: Array<ValidationError>;
}
