/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InitialOfficerInfo {
  computing_id: string;
  position: string;
  start_date: string;
}
