/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OfficerTermUpload {
  biography?: string | null;
  computing_id: string;
  end_date?: string | null;
  favourite_course_0?: string | null;
  favourite_course_1?: string | null;
  favourite_pl_0?: string | null;
  favourite_pl_1?: string | null;
  nickname?: string | null;
  photo_url?: string | null;
  position: string;
  start_date: string;
}
