/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OfficerInfoUpload {
  discord_name?: string | null;
  github_username?: string | null;
  google_drive_email?: string | null;
  legal_name: string;
  phone_number?: string | null;
}
