/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { ApiConfiguration } from '../api-configuration';
import { BaseService } from '../base-service';
import { StrictHttpResponse } from '../strict-http-response';

import { readRootGet, ReadRootGet$Params } from '../fn/operations/read-root-get';

@Injectable({ providedIn: 'root' })
export class ApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `readRootGet()` */
  static readonly ReadRootGetPath = '/';

  /**
   * Read Root.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `readRootGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  readRootGet$Response(
    params?: ReadRootGet$Params,
    context?: HttpContext
  ): Observable<StrictHttpResponse<any>> {
    return readRootGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Read Root.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `readRootGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  readRootGet(params?: ReadRootGet$Params, context?: HttpContext): Observable<any> {
    return this.readRootGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<any>): any => r.body)
    );
  }
}
