/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { ApiConfiguration } from '../api-configuration';
import { BaseService } from '../base-service';
import { StrictHttpResponse } from '../strict-http-response';

import {
  isAdminPermissionIsAdminGet,
  IsAdminPermissionIsAdminGet$Params
} from '../fn/permission/is-admin-permission-is-admin-get';

@Injectable({ providedIn: 'root' })
export class PermissionService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `isAdminPermissionIsAdminGet()` */
  static readonly IsAdminPermissionIsAdminGetPath = '/permission/is_admin';

  /**
   * Is Admin.
   *
   * checks if the current user has the admin permission
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `isAdminPermissionIsAdminGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  isAdminPermissionIsAdminGet$Response(
    params?: IsAdminPermissionIsAdminGet$Params,
    context?: HttpContext
  ): Observable<StrictHttpResponse<any>> {
    return isAdminPermissionIsAdminGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Is Admin.
   *
   * checks if the current user has the admin permission
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `isAdminPermissionIsAdminGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  isAdminPermissionIsAdminGet(
    params?: IsAdminPermissionIsAdminGet$Params,
    context?: HttpContext
  ): Observable<any> {
    return this.isAdminPermissionIsAdminGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<any>): any => r.body)
    );
  }
}
