/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { RequestBuilder } from '../../request-builder';
import { StrictHttpResponse } from '../../strict-http-response';

export interface LoginUserAuthLoginGet$Params {
  redirect_path: string;
  redirect_fragment: string;
  ticket: string;
}

export function loginUserAuthLoginGet(
  http: HttpClient,
  rootUrl: string,
  params: LoginUserAuthLoginGet$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, loginUserAuthLoginGet.PATH, 'get');
  if (params) {
    rb.query('redirect_path', params.redirect_path, {});
    rb.query('redirect_fragment', params.redirect_fragment, {});
    rb.query('ticket', params.ticket, {});
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

loginUserAuthLoginGet.PATH = '/auth/login';
