/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { RequestBuilder } from '../../request-builder';
import { StrictHttpResponse } from '../../strict-http-response';

export interface UpdateUserAuthUserPatch$Params {
  profile_picture_url: string;
}

export function updateUserAuthUserPatch(
  http: HttpClient,
  rootUrl: string,
  params: UpdateUserAuthUserPatch$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, updateUserAuthUserPatch.PATH, 'patch');
  if (params) {
    rb.query('profile_picture_url', params.profile_picture_url, {});
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

updateUserAuthUserPatch.PATH = '/auth/user';
